name: example
description: Example app for data_class_plugin
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   json_annotation: 4.7.0

dev_dependencies:
  lints: 2.0.0
  test: 1.21.6
  data_class_plugin:
    path: ../
